"""No-op writer. Useful for tests and disabled-diagnostic paths."""

from __future__ import annotations

import torch


class NullWriter:
    def add_scalar(self, tag: str, value: float, step: int) -> None: ...
    def add_histogram(self, tag: str, values: torch.Tensor, step: int) -> None: ...
    def add_image(self, tag: str, image: torch.Tensor, step: int,
                  dataformats: str = "CHW") -> None: ...
    def add_text(self, tag: str, text: str, step: int) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
